<?php

/**
 * @file
 * Contains cdstm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cdstm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cdstm module.
    case 'help.page.cdstm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cdstm_theme() {
  return [
    'cdstm' => [
      'render element' => 'children',
    ],
  ];
}
